config_file: /etc/kpow-rp/redpanda-2.yaml
node_uuid: RqZWm9oxGiMKPT2manMeSwbYcTqUYTBUTk7q9guRn3WTiju6a
pandaproxy:
  advertised_pandaproxy_api:
  - address: 127.0.0.1
    port: 8083
  pandaproxy_api:
  - address: 0.0.0.0
    port: 8083
redpanda:
  admin:
  - address: 0.0.0.0
    port: 9644
  advertised_kafka_api:
  - address: redpanda-2
    name: plaintext
    port: 29093
  - address: localhost
    name: outside
    port: 9093
  advertised_rpc_api:
    address: redpanda-2
    port: 33146
  auto_create_topics_enabled: true
  data_directory: /var/lib/redpanda/data
  default_topic_partitions: 18
  default_topic_replications: 3
  developer_mode: true
  kafka_api:
  - address: 0.0.0.0
    name: plaintext
    port: 29093
  - address: 0.0.0.0
    name: outside
    port: 9093
  node_id: 1
  rpc_server:
    address: 0.0.0.0
    port: 33146
  seed_servers:
  - host:
      address: redpanda-1
      port: 33145
rpk:
  coredump_dir: /var/lib/redpanda/coredump
  enable_memory_locking: false
  enable_usage_stats: true
  overprovisioned: true
  tune_aio_events: false
  tune_clocksource: false
  tune_coredump: false
  tune_cpu: false
  tune_disk_irq: false
  tune_disk_nomerges: false
  tune_disk_scheduler: false
  tune_disk_write_cache: false
  tune_fstrim: false
  tune_network: false
  tune_swappiness: false
  tune_transparent_hugepages: false
schema_registry: {}
